name: lda
favicon: null
layout_spectrum: 0.05057281022891402
typography_spectrum: 0.7630034561734647
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9127167055848986
  lightness: 0.2714673464652151
  saturation: 0.5641588103026152
  rhythmicContrast: 0.6622121708933264
purpose: []
